# Override file to use Python backend instead of Node
# Usage: docker compose -f compose.yaml -f compose.py.yaml up -d --build

services:
  api:
    build:
      context: ./services/api-py
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-app}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY:-}
      OPENROUTER_BASE_URL: ${OPENROUTER_BASE_URL:-https://openrouter.ai/api/v1}
      APP_NAME: ${APP_NAME:-project-starter}
      APP_URL: ${APP_URL:-http://localhost:8080}
      OPENROUTER_REASONING_MODEL: ${OPENROUTER_REASONING_MODEL:-}
      OPENROUTER_DEFAULT_MODEL: ${OPENROUTER_DEFAULT_MODEL:-}
