services:
  api:
    build:
      context: ./services/api-go
      dockerfile: Dockerfile
    environment:
      PORT: ${API_PORT:-8080}
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@db:5432/app}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY:-}
      OPENROUTER_BASE_URL: ${OPENROUTER_BASE_URL:-https://openrouter.ai/api/v1}
      APP_NAME: ${APP_NAME:-project-starter}
      APP_URL: ${APP_URL:-http://localhost:8080}
      OPENROUTER_REASONING_MODEL: ${OPENROUTER_REASONING_MODEL:-}
      OPENROUTER_DEFAULT_MODEL: ${OPENROUTER_DEFAULT_MODEL:-}
